# Bielik2D build helpers.
#
# Right now this is a thin layer: one `rake gen:constants` task that
# extracts SDL's `SDL_UINT64_C(...)` flag macros from the installed
# system headers and emits a plain Swift file. Swift's clang importer
# can't fold those macros into constants, so this just patches that
# blind spot without us having to hand-define each one.
#
# ---------------------------------------------------------------------
# Future direction (deliberately not done here)
#
# A richer wrapper generator could use Apple's SourceKit / swift-syntax
# to:
#   - parse the SDL C headers via libclang,
#   - emit typed Swift wrappers around SDL_GPU functions (closure-based
#     RAII for command buffers / render passes, throwing initializers
#     where the C call returns a nullable pointer, strongly-typed
#     handles instead of raw OpaquePointer, etc.),
#   - keep the generator and our hand-written API surface in sync
#     across SDL3 releases.
#
# That's a substantial project and we've explicitly scoped it out for
# v0. Hand-wrapped types in `Sources/Bielik2D/GPU/` are good enough
# until the wrapper count starts hurting. If/when we adopt swift-syntax,
# this Rakefile is the natural home for the `rake gen:wrappers` task
# that would replace the hand-written shims.
# ---------------------------------------------------------------------

require "pathname"

ROOT          = Pathname.new(__dir__).expand_path
GENERATED_DIR = ROOT / "Sources/Bielik2D/Generated"
GENERATED_OUT = GENERATED_DIR / "SDLConstants.swift"

# Homebrew's prefix varies by host (Apple Silicon: /opt/homebrew, Intel:
# /usr/local) and CI may differ, so resolve it rather than hard-coding. Honor
# an explicit HOMEBREW_PREFIX, fall back to `brew --prefix`, then a sane default.
BREW_PREFIX = ENV.fetch("HOMEBREW_PREFIX") do
  prefix = `brew --prefix 2>/dev/null`.strip
  prefix.empty? ? "/opt/homebrew" : prefix
end
BREW_INCLUDE = Pathname.new(BREW_PREFIX) / "include"

# Header directories scanned for macro definitions. Order matters: the
# first definition wins (we treat duplicates as a sanity check, not a
# merge).
HEADER_DIRS = [
  (BREW_INCLUDE / "SDL3").to_s,
  (BREW_INCLUDE / "SDL3_image").to_s,
  (BREW_INCLUDE / "SDL3_ttf").to_s,
  ROOT.join("vendor/.install/include/SDL3_shadercross").to_s,
].freeze

# Maps an SDL macro prefix to the Swift type it should be declared as.
# Anything unmatched falls back to UInt64.
PREFIX_TYPES = {
  "SDL_WINDOW_" => "SDL_WindowFlags",
}.freeze

UINT64_MACRO_RE = /
  ^\#define\s+
  (?<name>SDL_[A-Z0-9_]+)\s+
  SDL_UINT64_C\(\s*(?<value>0[xX][0-9a-fA-F]+)\s*\)
  (?:\s*\/\*\*?<?\s*(?<doc>.*?)\s*\*\/)?
/x

namespace :gen do
  desc "Generate Swift constants for SDL macros the Swift importer can't fold"
  task :constants do
    macros = {}

    HEADER_DIRS.each do |dir|
      Dir.glob(File.join(dir, "*.h")).sort.each do |header|
        File.foreach(header) do |line|
          next unless (m = line.match(UINT64_MACRO_RE))
          name = m[:name]
          next if macros.key?(name)  # first definition wins
          macros[name] = {
            value: m[:value],
            doc:   m[:doc],
            type:  PREFIX_TYPES.find { |p, _| name.start_with?(p) }&.last || "UInt64",
            from:  Pathname.new(header).basename.to_s,
          }
        end
      end
    end

    abort "No UINT64 macros found — are the SDL3 headers installed?" if macros.empty?

    GENERATED_DIR.mkpath
    File.open(GENERATED_OUT, "w") do |io|
      io.puts <<~SWIFT
        // Auto-generated by `rake gen:constants`. Do not edit by hand.
        //
        // These are SDL macro values that Swift's clang importer can't fold
        // because they use `SDL_UINT64_C(...)`. Re-run the rake task after
        // upgrading SDL to refresh the bindings.

        import CSDL3

      SWIFT

      grouped = macros.group_by { |_, info| info[:from] }
      grouped.sort.each do |source, entries|
        io.puts "// MARK: - #{source}"
        io.puts
        entries.sort.each do |name, info|
          io.puts "/// #{info[:doc]}" unless info[:doc].nil? || info[:doc].empty?
          io.puts "public let #{name}: #{info[:type]} = #{info[:value]}"
        end
        io.puts
      end
    end

    puts "wrote #{macros.size} constants to #{GENERATED_OUT.relative_path_from(ROOT)}"
  end
end

# ---------------------------------------------------------------------
# Dev convenience: thin wrappers over SwiftPM. Release variants matter
# because perf work must be measured with `-c release` (debug is 5-20×
# slower).

DEMO = "Bielik2DDemo".freeze

desc "Run the demo app (#{DEMO})"
task :run do
  sh "swift", "run", DEMO
end

namespace :run do
  desc "Run the demo app in release"
  task :release do
    sh "swift", "run", "-c", "release", DEMO
  end
end

desc "Build the package (debug)"
task :build do
  sh "swift", "build"
end

namespace :build do
  desc "Build the package in release"
  task :release do
    sh "swift", "build", "-c", "release"
  end
end

desc "Run the test suite"
task :test do
  sh "swift", "test"
end

task default: "gen:constants"
